import { Product, Category, Collection, Article, FAQ } from '@/types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Your Handcuffs or Mine',
    slug: 'your-handcuffs-or-mine',
    description: 'A playful and suggestive tee featuring our signature phrase. Perfect for those with a sense of humor and adventure.',
    price: 34.99,
    originalPrice: 39.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1503602642657-3e91760566f3?w=500&h=500&fit=crop',
    ],
    category: 'just-for-fun',
    collection: 'new-arrivals',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Deep Red'],
    stock: 45,
    featured: true,
    rating: 4.8,
    reviews: 24,
    tags: ['playful', 'conversation-starter', 'unisex'],
  },
  {
    id: 'prod-2',
    name: 'Deve8te Tee',
    slug: 'deve8te-tee',
    description: 'A wordplay on "deviate" - embrace your unique, non-standard self with this modern design.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1503602642657-3e91760566f3?w=500&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1503602642657-3e91760566f3?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    ],
    category: 'just-for-fun',
    collection: 'new-arrivals',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    stock: 32,
    featured: true,
    rating: 4.9,
    reviews: 18,
    tags: ['wordplay', 'minimalist', 'statement'],
  },
  {
    id: 'prod-3',
    name: 'Luxe Bondage Hoodie',
    slug: 'luxe-bondage-hoodie',
    description: 'Comfortable and stylish hoodie perfect for layering. Features subtle suggestive design.',
    price: 69.99,
    originalPrice: 79.99,
    image: 'https://images.unsplash.com/photo-1556821552-5db02d7dfc78?w=500&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556821552-5db02d7dfc78?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    ],
    category: 'bedroom-adventures',
    collection: 'bestsellers',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Deep Red'],
    stock: 28,
    featured: true,
    rating: 4.7,
    reviews: 15,
    tags: ['cozy', 'versatile', 'comfortable'],
  },
  {
    id: 'prod-4',
    name: 'Silk Binding Tie',
    slug: 'silk-binding-tie',
    description: 'Luxurious silk binding tie in deep red. Perfect for bedroom play or as a statement accessory.',
    price: 44.99,
    image: 'https://images.unsplash.com/photo-1625952562203-2bc2f7d96311?w=500&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1625952562203-2bc2f7d96311?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=500&fit=crop',
    ],
    category: 'accessories',
    collection: 'bestsellers',
    sizes: [],
    colors: ['Deep Red', 'Black'],
    stock: 67,
    featured: false,
    rating: 4.6,
    reviews: 12,
    tags: ['luxe', 'accessory', 'versatile'],
  },
  {
    id: 'prod-5',
    name: 'Mystery Long Sleeve',
    slug: 'mystery-long-sleeve',
    description: 'An elegant long sleeve with an air of mystery. Subtle design, maximum impact.',
    price: 44.99,
    image: 'https://images.unsplash.com/photo-1506218613502-7a4ae2412883?w=500&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1506218613502-7a4ae2412883?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    ],
    category: 'bedroom-adventures',
    collection: 'new-arrivals',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    stock: 41,
    featured: true,
    rating: 4.8,
    reviews: 20,
    tags: ['elegant', 'mysterious', 'versatile'],
  },
  {
    id: 'prod-6',
    name: 'Passion Pullover',
    slug: 'passion-pullover',
    description: 'A cozy pullover that speaks to your desires. Playful and suggestive design.',
    price: 54.99,
    image: 'https://images.unsplash.com/photo-1556821552-3b6461b4b36a?w=500&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556821552-3b6461b4b36a?w=500&h=500&fit=crop',
      'https://images.unsplash.com/photo-1503602642657-3e91760566f3?w=500&h=500&fit=crop',
    ],
    category: 'just-for-fun',
    collection: 'new-arrivals',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Deep Red'],
    stock: 35,
    featured: false,
    rating: 4.5,
    reviews: 9,
    tags: ['cozy', 'playful', 'suggestive'],
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    slug: 'bedroom-adventures',
    name: 'Bedroom Adventures',
    description: 'Explore our collection designed for intimate moments and playful exploration.',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500&h=300&fit=crop',
    subcategories: [
      { id: 'subcat-1', slug: 'tshirts', name: 'T-Shirts', productType: 't-shirt' },
      { id: 'subcat-2', slug: 'long-sleeve', name: 'Long Sleeve', productType: 'long-sleeve' },
      { id: 'subcat-3', slug: 'hoodies', name: 'Hoodies', productType: 'hoodie' },
    ],
  },
  {
    id: 'cat-2',
    slug: 'accessories',
    name: 'Accessories',
    description: 'Enhance your experience with our carefully curated accessories collection.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=300&fit=crop',
    subcategories: [
      { id: 'subcat-4', slug: 'ties-ribbons', name: 'Ties & Ribbons', productType: 'tie' },
      { id: 'subcat-5', slug: 'masks', name: 'Masks', productType: 'mask' },
      { id: 'subcat-6', slug: 'other', name: 'Other', productType: 'accessory' },
    ],
  },
  {
    id: 'cat-3',
    slug: 'just-for-fun',
    name: 'Just for Fun',
    description: 'Playful and suggestive apparel with witty designs and conversation starters.',
    image: 'https://images.unsplash.com/photo-1612150506803-2402d00bb653?w=500&h=300&fit=crop',
    subcategories: [
      { id: 'subcat-7', slug: 'tshirts', name: 'T-Shirts', productType: 't-shirt' },
      { id: 'subcat-8', slug: 'hoodies', name: 'Hoodies', productType: 'hoodie' },
      { id: 'subcat-9', slug: 'pullover', name: 'Pullovers', productType: 'pullover' },
    ],
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    slug: 'new-arrivals',
    name: 'New Arrivals',
    description: 'Check out our latest designs and products',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=400&fit=crop',
    link: '/collections/new-arrivals',
    featured: true,
  },
  {
    id: 'col-2',
    slug: 'bestsellers',
    name: 'Best Sellers',
    description: 'Our most popular items that customers love',
    image: 'https://images.unsplash.com/photo-1506629082632-1b91c001e541?w=800&h=400&fit=crop',
    link: '/collections/bestsellers',
    featured: true,
  },
  {
    id: 'col-3',
    slug: 'sale',
    name: 'On Sale',
    description: 'Limited time offers on selected items',
    image: 'https://images.unsplash.com/photo-1545705925-e839bdb77e5b?w=800&h=400&fit=crop',
    link: '/collections/sale',
    featured: true,
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: 'art-1',
    slug: 'style-guide-mystery',
    title: 'The Art of Mystery: A Style Guide',
    excerpt: 'Discover how to incorporate mystery and intrigue into your everyday wardrobe.',
    content: 'Comprehensive guide on building a mysterious and alluring personal style...',
    author: 'Fashion Editor',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=400&fit=crop',
    publishedAt: '2024-01-15',
    tags: ['style', 'fashion', 'guide'],
  },
  {
    id: 'art-2',
    slug: 'confidence-apparel',
    title: 'Confidence Through Apparel',
    excerpt: 'How the right clothing can boost your confidence and self-expression.',
    content: 'Explore the psychology of fashion and personal empowerment...',
    author: 'Style Contributor',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=400&fit=crop',
    publishedAt: '2024-01-10',
    tags: ['confidence', 'style', 'empowerment'],
  },
  {
    id: 'art-3',
    slug: 'playful-fashion-statement',
    title: 'Making a Playful Fashion Statement',
    excerpt: 'Express your unique personality through bold and suggestive fashion choices.',
    content: 'Learn how to choose pieces that reflect your authentic self...',
    author: 'Fashion Editor',
    image: 'https://images.unsplash.com/photo-1558769225-fc52792ca185?w=800&h=400&fit=crop',
    publishedAt: '2024-01-05',
    tags: ['fashion', 'personal-style', 'expression'],
  },
];

export const MOCK_FAQS: FAQ[] = [
  {
    id: 'faq-1',
    question: 'What is the return policy?',
    answer: 'We offer a 30-day return policy for all items in original condition with tags attached. Returns are free and easy through our online portal.',
    category: 'orders',
  },
  {
    id: 'faq-2',
    question: 'How long does shipping take?',
    answer: 'Standard shipping takes 5-7 business days. Express shipping is available for 2-3 business day delivery. Free shipping on orders over $75.',
    category: 'shipping',
  },
  {
    id: 'faq-3',
    question: 'Is my information secure?',
    answer: 'Yes, we use industry-standard SSL encryption and PCI compliance to protect all your personal and payment information.',
    category: 'security',
  },
  {
    id: 'faq-4',
    question: 'Do you ship internationally?',
    answer: 'We currently ship to select international locations. Shipping costs and times vary by destination. Please check during checkout for availability.',
    category: 'shipping',
  },
  {
    id: 'faq-5',
    question: 'How do I care for my items?',
    answer: 'All items include care instructions on the tag. Generally, we recommend washing in cold water and drying on low heat to maintain quality.',
    category: 'care',
  },
  {
    id: 'faq-6',
    question: 'What payment methods do you accept?',
    answer: 'We accept all major credit cards, PayPal, Apple Pay, and Google Pay for secure transactions.',
    category: 'payments',
  },
];
